name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Print working directory
      run: pwd
    - name: List files in the root directory
      run: ls -la
    - name: Change to project directory
      run: cd nextjs-fastapi-framework-main
    - name: List files in the project directory
      run: ls -la nextjs-fastapi-framework-main
    - name: Build the Docker image
      run: docker build nextjs-fastapi-framework-main --file nextjs-fastapi-framework-main/Dockerfile --tag my-image-name:$(date +%s)
