name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List files in the directory
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file docker-image.yml --tag my-image-name:$(date +%s)
